#Makefile to produce the B option executable, all commands start with a tab

cat Makefile
	gcc -o report driver.o fica.o gross.o
	gcc -c -o driver.o Src_directory/driver.c
	gcc -c -o fica.o Src_directory/fica.c
	gcc -c -o gross.o Src_directory/gross.c
make createReport
./report

